// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydyvlnpqbuioonndnusk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkeXZsbnBxYnVpb29ubmRudXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDU1NjYsImV4cCI6MjA1ODU4MTU2Nn0.Y4JYxzcRvp8xn85G06h1JSjJ1B5-f1_Ywj2amPckSDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);